[workspace]
members = [
  "crates/module",
  "crates/mc173-module",
  "crates/mc173-server",
]
default-members = ["crates/module"]
# cargo feature graph resolver. v2 is default in edition2021 but workspace
# manifests don't have editions.
resolver = "2"
